project:
  type: website
  # lib-dir: lib
  output-dir: _site
  pre-render:
    - ../tools/typstdoc/main.lua
  resources:
    - assets/fonts/
    - assets/images/logo.svg
    - assets/images/logo-dark.svg
    - assets/images/logo-stacked.svg
    - assets/images/logo-stacked-dark.svg
    - assets/images/favicon.svg
    - assets/images/favicon-dark.svg
    - assets/images/social-card.png

lang: en-GB
date-format: "dddd[, the] Do [of] MMMM, YYYY"
image: /assets/images/social-card.png

website:
  title: "Gribouille"
  description: "Create elegant graphics with the Grammar of Graphics for Typst."
  favicon: assets/images/favicon.svg
  site-url: https://m.canouil.dev/gribouille
  repo-url: https://github.com/mcanouil/gribouille
  repo-actions: [ edit, issue ]
  repo-link-target: _blank
  repo-link-rel: noopener noreferrer
  open-graph: true
  twitter-card: true
  page-navigation: true
  back-to-top-navigation: true
  llms-txt: true

  page-footer:
    border: true
    left: |
      Powered by [{{< iconify simple-icons:quarto title="Quarto Logo" label="Quarto Logo" >}} Quarto](https://quarto.org).
    center: |
      &copy; []{#current-year} [Mickaël CANOUIL](https://mickael.canouil.fr). [{{< iconify octicon:heart-fill-16 title="Heart" label="Heart" >}} Sponsor](https://github.com/sponsors/mcanouil?o=esb).
    right: |
      Licence: [MIT](https://github.com/mcanouil/gribouille?tab=MIT-1-ov-file#readme).

  navbar:
    title: "Gribouille"
    logo: assets/images/logo-dark.svg
    logo-alt: "Gribouille"
    background: dark
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "Get Started"
        href: get-started/index.qmd
      - text: "Guides"
        menu:
          - text: "Theming"
            href: guides/theming.qmd
          - text: "Accessibility"
            href: guides/accessibility.qmd
      - text: "Reference"
        href: reference/index.qmd
      - text: "Examples"
        href: examples/index.qmd
      - text: "News"
        href: news/index.qmd
    right:
      - text: "{{< iconify octicon:tag-16 title=\"Current version\" label=\"Current version\" >}} {{< env VERSION >}}"
        menu:
          - text: "{{< iconify simple-icons:typst title=\"Typst Universe\" label=\"Typst
              Universe\" >}} Typst Universe"
            href: https://typst.app/universe/package/gribouille
          - text: "{{< iconify octicon:repo-16 title=\"GitHub repository\" label=\"GitHub
              repository\" >}} Source code"
            href: https://github.com/mcanouil/gribouille
          - text: "{{< iconify octicon:tag-16 title=\"All releases\" label=\"All releases\"
              >}} All releases"
            href: https://github.com/mcanouil/gribouille/releases
          - text: "{{< iconify octicon:history-16 title=\"Changelog\" label=\"Changelog\"
              >}} Changelog"
            href: changelog.qmd
          - text: "---"
          - text: "{{< iconify octicon:versions-16 title=\"Switch version\" label=\"Switch
              version\" >}} {{< env VERSION_SWITCH >}}"
            href: "{{< env VERSION_SWITCH_URL >}}"
      - text: "{{< iconify octicon:heart-fill-16 title=\"Sponsor\" label=\"Sponsor\"
          >}}"
        href: https://github.com/sponsors/mcanouil?o=esb
        aria-label: "Sponsor"

brand: _brand.yml

format:
  html:
    toc: true
    toc-depth: 3
    code-copy: true
    code-link: false
    code-overflow: wrap
    link-external-newwindow: true
    fig-align: center
    grid:
      sidebar-width: 300px
      body-width: 1100px
      margin-width: 300px
    theme:
      light:
        - cosmo
        - brand
        - assets/stylesheets/theme.scss
      dark:
        - cosmo
        - brand
        - assets/stylesheets/theme.scss
    syntax-highlighting:
      light: github-light
      dark: github-dark
    include-after-body:
      - file: assets/scripts/current-year.html
      - file: assets/scripts/external-links.html
      - file: assets/scripts/gallery-toc.html
      - file: assets/scripts/ordinal-dates.html
      - file: assets/scripts/tooltips.html

execute:
  freeze: false

lightbox: auto

metadata-files:
  - _extensions-metadata.yml
  - _sidebar-reference.yml
  - _sidebar-get-started.yml
  - _sidebar-examples.yml
