local util = require("util")

local M = {}

local LEGACY_MARKER_OPEN = "# >>> typstdoc (managed block; do not edit between markers)"
local LEGACY_MARKER_CLOSE = "# <<< typstdoc"

local PREAMBLE_FILENAME = "_typst-preamble.typ"
local PREAMBLE_CONTENT = [[
// Managed by typstdoc. Preamble prepended to every rendered @example block.
#import "/lib.typ": *
]]

local EXTENSIONS_METADATA_FILENAME = "_extensions-metadata.yml"
local EXTENSIONS_METADATA_CONTENT = string.format([[
# Generated by typstdoc. Do not edit: re-run `lua tools/typstdoc/main.lua` to update.
filters:
  - typst-render

extensions:
  typst-render:
    root: ".."
    preamble: "%s"
    output-directory: "assets/typst-render"
    background: auto
    width: auto
    height: auto
    margin: 0pt
]], PREAMBLE_FILENAME)

local function escape_pattern(s)
  return (s:gsub("([%(%)%.%%%+%-%*%?%[%]%^%$])", "%%%1"))
end

local function find_legacy_block(content)
  local start_s = content:find(escape_pattern(LEGACY_MARKER_OPEN))
  if not start_s then return nil end
  local _, end_e = content:find(escape_pattern(LEGACY_MARKER_CLOSE), start_s, false)
  if not end_e then return nil end
  return start_s, end_e
end

local function remove_legacy_block(content)
  local start_s, end_e = find_legacy_block(content)
  if not start_s then return content end
  local before = content:sub(1, start_s - 1):gsub("\n*$", "")
  local after = content:sub(end_e + 1):gsub("^\n*", "")
  if before ~= "" and after ~= "" then
    return before .. "\n\n" .. after
  end
  if before == "" and after == "" then return "" end
  if before == "" then return after end
  return before .. "\n"
end

function M.patch_metadata_yml(path)
  local content = util.read_file(path)
  if not content then return false end
  local updated = remove_legacy_block(content)
  if updated ~= content then
    util.write_file(path, updated)
    return true
  end
  return false
end

local function has_metadata_entry(content, filename)
  local esc = escape_pattern(filename)
  return content:find("\n%s*%-%s*" .. esc .. "%s*\n") ~= nil
    or content:find("^%s*%-%s*" .. esc .. "%s*\n") ~= nil
end

local function insert_metadata_entry(content, filename)
  local key_pos = content:find("metadata%-files:%s*\n")
  local insertion = "  - " .. filename .. "\n"
  if key_pos then
    local key_end = content:find("\n", key_pos, true)
    return content:sub(1, key_end) .. insertion .. content:sub(key_end + 1)
  end
  if content ~= "" and content:sub(-1) ~= "\n" then content = content .. "\n" end
  return content .. "\nmetadata-files:\n" .. insertion
end

function M.patch_quarto_yml(path, sidebar_filename)
  local content = util.read_file(path)
  if not content then
    util.log_warn("cannot read " .. path .. ", skipping navbar patch")
    return false
  end
  local original = content

  content = remove_legacy_block(content)

  if not has_metadata_entry(content, sidebar_filename) then
    content = insert_metadata_entry(content, sidebar_filename)
  end
  if not has_metadata_entry(content, EXTENSIONS_METADATA_FILENAME) then
    content = insert_metadata_entry(content, EXTENSIONS_METADATA_FILENAME)
  end

  local patched, n = content:gsub("href:%s*reference%.qmd", "href: reference/index.qmd", 1)
  if n > 0 then content = patched end

  local docs_dir = path:match("(.*)/[^/]+$") or "."

  local preamble_path = docs_dir .. "/" .. PREAMBLE_FILENAME
  local existing_preamble = util.read_file(preamble_path)
  if existing_preamble ~= PREAMBLE_CONTENT then
    util.write_file(preamble_path, PREAMBLE_CONTENT)
  end

  local extensions_path = docs_dir .. "/" .. EXTENSIONS_METADATA_FILENAME
  local existing_extensions = util.read_file(extensions_path)
  if existing_extensions ~= EXTENSIONS_METADATA_CONTENT then
    util.write_file(extensions_path, EXTENSIONS_METADATA_CONTENT)
  end

  if content ~= original then
    util.write_file(path, content)
    return true
  end
  return false
end

M._EXTENSIONS_METADATA_FILENAME = EXTENSIONS_METADATA_FILENAME
M._EXTENSIONS_METADATA_CONTENT = EXTENSIONS_METADATA_CONTENT

return M
